Style/Documentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/IfUnlessModifier: 
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Lint/DuplicateRequire:
  Enabled: false
